# Generated by Django 5.1.5 on 2025-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0002_tag_alter_document_options_document_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='original_document',
            field=models.FileField(default=1, upload_to='documents/%{pk}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_version_document',
            field=models.FileField(blank=True, upload_to='documents/pdf/{pk}'),
        ),
    ]
