# Generated by Django 5.1.5 on 2025-03-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0003_remove_document_document_document_original_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='original_document',
            new_name='original_file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='pdf_version_document',
            new_name='pdf_file_version',
        ),
    ]
