# Generated by Django 5.1.5 on 2025-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_documents', '0004_rename_original_document_document_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(upload_to='documents/{uuid}/{uuid}'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file_version',
            field=models.FileField(blank=True, upload_to='documents/pdf/{uuid}/{uuid}'),
        ),
    ]
